Đề Thi Thực Hành Đại Số Tuyến Tính

Câu 1: Phép toán cơ bản trên vector và ma trận (15 điểm)

In [1]:
import numpy as np
from math import acos, degrees
A = np.array([3, -2, 1, 4])
B = np.array([-1, 5, 0, 2])
C = np.array([[2, -1, 3],
              [1, 4, -2],
              [0, 2, 5]])
sum_AB = A + B
linear_combo = 2 * A + 3 * B
print("a)")
print("A + B =", sum_AB)
print("2A + 3B =", linear_combo)
dot_product = np.dot(A, B)
norm_A = np.linalg.norm(A)
norm_B = np.linalg.norm(B)
cos_theta = dot_product / (norm_A * norm_B)
angle_deg = degrees(acos(cos_theta))
print("\nb)")
print("A · B =", dot_product)
print("Góc giữa A và B (độ) ≈", round(angle_deg, 3))
CCT = C @ C.T
print("\nc)")
print("Ma trận CC^T =")
print(CCT)

a)
A + B = [2 3 1 6]
2A + 3B = [ 3 11  2 14]

b)
A · B = -5
Góc giữa A và B (độ) ≈ 99.594

c)
Ma trận CC^T =
[[14 -8 13]
 [-8 21 -2]
 [13 -2 29]]


Câu 2: Nhân ma trận, định thức và hạng ma trận (20 điểm)

In [2]:
import numpy as np
M = np.array([[2, -1, 3, 0],
              [1, 4, -2, 5],
              [0, 2, 6, -3],
              [-1, 0, 1, 4]])
N = np.array([[1, 3, -2, 0],
              [4, -1, 5, 2],
              [0, 2, 3, -1],
              [-3, 1, 0, 4]])
MN = M @ N
print("a)")
print("M × N =")
print(MN)
try:
    det_M = np.linalg.det(M)
    print("\nb)")
    print("Định thức của M =", round(det_M, 3))
except np.linalg.LinAlgError:
    print("\nb)")
    print("Không thể tính định thức của M (ma trận không vuông)")
rank_N = np.linalg.matrix_rank(N)
print("\nc)")
print("Hạng của ma trận N =", rank_N)

a)
M × N =
[[ -2  13   0  -5]
 [  2   0  12  30]
 [ 17   7  28 -14]
 [-13   3   5  15]]

b)
Định thức của M = 409.0

c)
Hạng của ma trận N = 4


Câu 3: Nghịch đảo ma trận và giải hệ phương trình (25 điểm)

In [3]:
import numpy as np
P = np.array([[3, -1, 0, 2],
              [1, 4, -2, 0],
              [0, 1, 5, -1],
              [2, 0, 1, 3]])
b = np.array([6, 8, 3, 7])
try:
    P_inv = np.linalg.inv(P)
    print("a)")
    print("Nghịch đảo của P:")
    print(np.round(P_inv, 3))
except np.linalg.LinAlgError:
    print("a)")
    print("Ma trận P không khả nghịch.")
x = P_inv @ b
print("\nb)")
print("Nghiệm của hệ phương trình:")
print(np.round(x, 3))
check = P @ x
print("\nc)")
print("P @ x =")
print(np.round(check, 3))
print("So với vector hằng số b:")
print(b)

a)
Nghịch đảo của P:
[[ 0.5    0.1    0.1   -0.3  ]
 [-0.143  0.2    0.057  0.114]
 [-0.036 -0.05   0.164  0.079]
 [-0.321 -0.05  -0.121  0.507]]

b)
Nghiệm của hệ phương trình:
[2.    1.714 0.429 0.857]

c)
P @ x =
[6. 8. 3. 7.]
So với vector hằng số b:
[6 8 3 7]


Câu 4: Giá trị riêng, vector riêng và chuẩn hóa (20 điểm)

In [7]:
import numpy as np
Q = np.array([[5, -2, 1],
              [0, 3, -1],
              [2, 0, 4]])
eigvals, eigvecs = np.linalg.eig(Q)
print("a)")
print("Giá trị riêng:")
print(np.round(eigvals, 3))
print("\nb)")
print("Vector riêng ứng với các giá trị riêng (cột là từng vector):")
print(np.round(eigvecs, 3))
norm_vecs = eigvecs / np.linalg.norm(eigvecs, axis=0)
print("\nc)")
print("Vector riêng sau khi chuẩn hóa (mỗi vector có độ dài = 1):")
print(np.round(norm_vecs, 3))

a)
Giá trị riêng:
[6.355+0.j    2.822+1.077j 2.822-1.077j]

b)
Vector riêng ứng với các giá trị riêng (cột là từng vector):
[[ 0.748+0.j    -0.374+0.342j -0.374-0.342j]
 [-0.189+0.j     0.095+0.574j  0.095-0.574j]
 [ 0.636+0.j     0.636+0.j     0.636-0.j   ]]

c)
Vector riêng sau khi chuẩn hóa (mỗi vector có độ dài = 1):
[[ 0.748+0.j    -0.374+0.342j -0.374-0.342j]
 [-0.189+0.j     0.095+0.574j  0.095-0.574j]
 [ 0.636+0.j     0.636+0.j     0.636-0.j   ]]


Câu 5: Ứng dụng thực tế - Hệ phương trình và phân tích (20
điểm)

In [6]:
import numpy as np
R = np.array([[4, -1, 2],
              [1, 3, -2],
              [0, 2, 5]])
b = np.array([12, 5, 9])
z = np.linalg.solve(R, b)
print("a)")
print("Nghiệm z của phương trình Rz = b:")
print(np.round(z, 3))
try:
    R_inv = np.linalg.inv(R)
    z_check = R_inv @ b
    print("\nb)")
    print("Ma trận nghịch đảo của R:")
    print(np.round(R_inv, 3))
    print("Nghiệm tính lại bằng R⁻¹ · b:")
    print(np.round(z_check, 3))
except np.linalg.LinAlgError:
    print("\nb)")
    print("Ma trận R không khả nghịch.")
fro_norm = np.linalg.norm(R, ord='fro')
print("\nc)")
print("Chuẩn Frobenius của ma trận R =", round(fro_norm, 3))

a)
Nghiệm z của phương trình Rz = b:
[2.788 1.529 1.188]

b)
Ma trận nghịch đảo của R:
[[ 0.224  0.106 -0.047]
 [-0.059  0.235  0.118]
 [ 0.024 -0.094  0.153]]
Nghiệm tính lại bằng R⁻¹ · b:
[2.788 1.529 1.188]

c)
Chuẩn Frobenius của ma trận R = 8.0
