1. Sử dụng array và matrix trong numpy

1.1. Thông tin tóm gọn

In [5]:
import numpy as np
D = np.array([[1, 2], [3, 4]])
E = np.empty_like(D)
np.copyto(E, D)

In [6]:
E = np.array([[1,2],[3,5]])
np.copyto(E, D)

In [7]:
print(E)

[[1 2]
 [3 4]]


1.2. Nên và không nên sử dụng kiểu dữ liệu numpy.matrix

In [9]:
import numpy as np
C = np.matrix([[1,2],[3, 4]] )
print(C)

[[1 2]
 [3 4]]


In [11]:
A = np.matrix([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


In [12]:
A = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(A)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


1.3. Đối tượng matrix từ các hàm trong gói numpy.matlib

In [13]:
from numpy import matlib
G = matlib.identity(5)
print(G)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:
H = matlib.randn(3, 2)
print(H)

[[ 1.41858676 -0.74110987]
 [ 0.05151385  0.49107174]
 [-0.33021122  1.06351115]]


In [15]:
K = matlib.zeros([4, 4])
print(K)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


2. Ứng dụng 2

2.1. Liên phân số

2.2. Liên phân số biểu diễn số Pi

In [17]:
import numpy as np

c = [3, 7, 15, 1, 292, 1, 1, 1, 2, 1, 3, 1, 14, 2]

M = np.asmatrix([[1, 2], [3, 4]])

for i in range(len(c)):
    ci = np.asmatrix([[1, 1], [1, 0]])
    ci[0, 0] = c[i]
    if i == 0:
        M = ci
    else:
        M = M.dot(ci)

print(M)
print(M[0, 0] / M[1, 0])

[[165707065  80143857]
 [ 52746197  25510582]]
3.1415926535897936


3. Về phân tích hồi quy tuyến tính

3.1. Dẫn nhập: khái niệm về sai số

3.2. Phương pháp bình phương cực tiểu (mô hình tuyến tính)

In [18]:
import numpy as np

X = np.array([
    [1, 0],
    [1, 1],
    [1, 2],
    [1, 3]
])

Y = np.array([
    [1],
    [2],
    [3],
    [4]
])

In [19]:
XT = X.T

In [20]:
A1 = np.linalg.inv(XT.dot(X))
A2 = XT.dot(Y)

In [21]:
A = A1.dot(A2)
print("A =", A)


A = [[1.]
 [1.]]


In [22]:
Y_pred = X.dot(A)
error = Y - Y_pred
squared_error_sum = np.sum(np.square(error))
print("Tổng sai số bình phương:", squared_error_sum)

Tổng sai số bình phương: 1.1044052673094165e-29


BÀI TẬP CHƯƠNG 5

Câu 1:

In [23]:
import numpy as np

def bpcuctieu(a):
    b = []
    o1 = []
    for i in range(len(a)):
        o1.append(1.0)
        b.append(i * 1.0)

    x = np.array([o1, b])
    u = np.dot(x, x.T)
    y = np.array(a)

    from numpy import linalg
    u_1 = np.linalg.inv(u)
    v = np.dot(u_1, x)
    A = np.dot(v, y)

    return A

dulieu = [10.0, 8, 7, 5, 2]
A = bpcuctieu(dulieu)

print(f"Phương trình tuyến tính: y = {A[0]:.2f} + {A[1]:.2f} * x")


Phương trình tuyến tính: y = 10.20 + -1.90 * x
