1.2.1

In [1]:
danhsach1 = [1., 3.]
danhsach2 = [5., 7.]
danhsach = danhsach1 + danhsach2
danhsach

[1.0, 3.0, 5.0, 7.0]

In [2]:
danhsach_gapdoi = 2 * danhsach
danhsach_gapdoi

[1.0, 3.0, 5.0, 7.0, 1.0, 3.0, 5.0, 7.0]

In [3]:
danhsach * 2

[1.0, 3.0, 5.0, 7.0, 1.0, 3.0, 5.0, 7.0]

In [4]:
danhsach / 2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [5]:
mon_hoc = ["ToanCC", "DSTT", "ToanRR", "LaptrinhCB"]
thu_tu = [2, 3, 4, 1]
diem_so = [10, 9, 8, 7]
anh_xa = zip(thu_tu, mon_hoc, diem_so)
anh_xa

In [6]:
tap_hop = set(anh_xa)
tap_hop

{(1, 'LaptrinhCB', 7), (2, 'ToanCC', 10), (3, 'DSTT', 9), (4, 'ToanRR', 8)}

In [7]:
anh_xa = zip(thu_tu, mon_hoc, diem_so)
lay_TT, lay_monhoc, lay_diem = zip(*anh_xa)
lay_monhoc

('ToanCC', 'DSTT', 'ToanRR', 'LaptrinhCB')

In [8]:
ds = [1, 2, 3, 4]

In [9]:
ds = []
ds.append(1)
ds.append(2)
ds

[1, 2]

In [10]:
ds = [x**2 for x in range(5)]
ds

[0, 1, 4, 9, 16]

In [11]:
ds = list(range(5))
ds

[0, 1, 2, 3, 4]

In [12]:
list(zip(range(4), range(7, 12), reversed(range(11))))

[(0, 7, 10), (1, 8, 9), (2, 9, 8), (3, 10, 7)]

1.2.2

In [14]:
a = 10
b = 20
c = a + b
mylist.append(c)
print("Trong thucthi1.py:", a, b, c, mylist)

Trong thucthi1.py: 10 20 30 [30]


2.1

In [17]:
from sympy import Symbol
x = Symbol('x')
f = x + x + x + 2
f

3*x + 2

In [18]:
a = Symbol('Noi')
b = Symbol('Chim')
3*b + 7*a

3*Chim + 7*Noi

In [19]:
a = Symbol('Noi')
b = Symbol('Chim')
a.name

'Noi'

In [20]:
b.name

'Chim'

In [21]:
from sympy import Symbol
x = Symbol('x')
y = Symbol('y')
s = x*y + y*x
s

2*x*y

In [22]:
p = x*(x + 2*x)
p

3*x**2

In [23]:
p = (x + 2)*(y + 3)
p

(x + 2)*(y + 3)

In [24]:
p = (x + 2)*(y + 3) + (x + 2)*(x - 3)
p

(x - 3)*(x + 2) + (x + 2)*(y + 3)

In [25]:
p = x*(-x + 2*x - x)
p

0

In [26]:
p = (x + 2)*(y + 3)
p.expand()

x*y + 3*x + 2*y + 6

2.2.1

In [27]:
from sympy import Symbol, factor, expand

x = Symbol('x')
y = Symbol('y')

bieuthuc = x**3 - y**3
factor(bieuthuc)

(x - y)*(x**2 + x*y + y**2)

In [28]:
bieuthuc = (x - y)*(x**2 + x*y + y**2)
expand(bieuthuc)

x**3 - y**3

2.2.3

In [29]:
from sympy import Symbol
x = Symbol('x')
y = Symbol('y')
bieuthuc = x*x - x*y + y*y
bieuthuc

x**2 - x*y + y**2

In [30]:
giatri = bieuthuc.subs({x:3, y:2})
giatri

7

In [31]:
x

x

In [32]:
y

y

tình huống 1

In [33]:
giatri = bieuthuc.subs({x:3, y:x})
giatri

x**2 - 3*x + 9

tình huống 2

In [34]:
giatri = bieuthuc.subs({x:y, y:3})
giatri

9

tình huống 3

In [35]:
giatri = bieuthuc.subs({y:x}).subs({x:3})
giatri

9

In [36]:
from sympy import Symbol
x = Symbol('x')
y = Symbol('y')
bieuthuc = x*x - x*y + y*y
bieuthuc

x**2 - x*y + y**2

In [37]:
bieuthuc_moi = bieuthuc.subs({x:1 - y})
bieuthuc_moi

y**2 - y*(1 - y) + (1 - y)**2

In [38]:
from sympy import simplify
dongian = simplify(bieuthuc_moi)
dongian

3*y**2 - 3*y + 1

In [40]:
from sympy import Symbol, sin, cos, simplify
x = Symbol('x')
y = Symbol('y')
bt = sin(x)*cos(y) + cos(x)*sin(y)
bt_moi = simplify(bt)
bt_moi

sin(x + y)

3.1

In [41]:
import numpy as np

In [42]:
from numpy import *

3.2

In [43]:
vec1 = np.array([1., 3., 5.])
vec1 * 2

array([ 2.,  6., 10.])

In [44]:
vec1 * vec1

array([ 1.,  9., 25.])

In [45]:
vec1 /2

array([0.5, 1.5, 2.5])

In [46]:
vec1 + vec1

array([ 2.,  6., 10.])

In [49]:
vec2 = array([2., 4.])
vec1 + vec2

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [50]:
vec3 = array([2., 4., 6.])
vec1 + vec3

array([ 3.,  7., 11.])

In [51]:
vec1 / vec3

array([0.5       , 0.75      , 0.83333333])

In [52]:
vec1 * vec3

array([ 2., 12., 30.])

In [53]:
2 * vec1 + 5 * vec3

array([12., 26., 40.])

In [54]:
vec3[2]

np.float64(6.0)

In [55]:
vec4 = np.linspace(0, 20, 5)
vec4

array([ 0.,  5., 10., 15., 20.])

In [59]:
vec5 = np.zeros(5)

In [60]:
vec6 = np.ones(5)

In [61]:
vec7 = np.empty(5)

In [62]:
np.random.random(5)

array([0.07520208, 0.11830259, 0.7257498 , 0.53141985, 0.36434631])

In [63]:
v = np.array([1., 3., 5.])

In [64]:
np.sum(v)

np.float64(9.0)

In [65]:
v.shape

(3,)

In [66]:
v.transpose()

array([1., 3., 5.])

In [67]:
v1 = v[:2]
v1

array([1., 3.])

In [68]:
v[0] = 5
v

array([5., 3., 5.])

In [69]:
v1[:2] = [1., 2., 3.]

ValueError: could not broadcast input array from shape (3,) into shape (2,)

In [70]:
v1[:2] = [1., 2]
v

array([1., 2., 5.])

In [73]:
v3 = 2 * v[:2] + v1 * 3

ValueError: operands could not be broadcast together with shapes (2,) (6,) 

In [72]:
v1 = [4, 6]
v3

array([ 5., 10.])

In [74]:
v

array([1., 2., 5.])

In [75]:
v + 10.0

array([11., 12., 15.])

In [76]:
np.sqrt(v)

array([1.        , 1.41421356, 2.23606798])

In [77]:
np.cos(v)

array([ 0.54030231, -0.41614684,  0.28366219])

In [78]:
np.sin(v)

array([ 0.84147098,  0.90929743, -0.95892427])

In [82]:
np.dot(v1, v3)

np.float64(80.0)

In [87]:
v1.dot(v3)

np.float64(125.0)

In [88]:
v3.dot(v1)

np.float64(125.0)

Bài tập 1

In [89]:
from sympy import Symbol, solve
x = Symbol('x')
bieuthuc = x + 3 - 5
solve(bieuthuc)

[2]

In [90]:
bieuthuc = x**2 + 3 - 5
nghiemx = solve(bieuthuc)
nghiemx

[-sqrt(2), sqrt(2)]

In [91]:
nghiemx[0]

-sqrt(2)

In [92]:
nghiemx[1]

sqrt(2)

Bài tập 2

In [93]:
from sympy import Symbol, solve
x = Symbol('x')
ptb2 = x**2 + 9*x + 8
solve(ptb2, dict=True)

[{x: -8}, {x: -1}]

In [94]:
ptb2 = x**2 + x + 10
nghiemx = solve(ptb2, dict=True)
nghiemx

[{x: -1/2 - sqrt(39)*I/2}, {x: -1/2 + sqrt(39)*I/2}]

Bài tập 3

In [95]:
from sympy import Symbol, solve

x = Symbol('x')
a = Symbol('a')
b = Symbol('b')
c = Symbol('c')

ptb2 = a*x**2 + b*x + c
nghiem = solve(ptb2, x, dict=True)
nghiem

[{x: (-b - sqrt(-4*a*c + b**2))/(2*a)}, {x: (-b + sqrt(-4*a*c + b**2))/(2*a)}]

In [96]:
from sympy import Symbol, solve

x = Symbol('x')
y = Symbol('y')
pt1 = 2*x + 3*y - 12
pt2 = 3*x - 2*y - 5
solve((pt1, pt2), dict=True)

[{x: 3, y: 2}]

In [97]:
nghiem = solve((pt1, pt2), dict=True)
nghiem = nghiem[0]
pt1.subs({x:nghiem[x], y:nghiem[y]})

0

In [98]:
pt2.subs({x:nghiem[x], y:nghiem[y]})

0

Bài tập 5

In [99]:
M1 = np.array([[9, 12], [23, 30]])
u = np.array([2, 1])
tichM1u = M1.dot(u)
print(tichM1u)

[30 76]


In [100]:
tichuM1 = u.dot(M1)
print(tichuM1)

[41 54]


In [101]:
np.dot(M1, u)

array([30, 76])

In [102]:
np.dot(u, M1)

array([41, 54])

In [106]:
mat1 = np.zeros([5, 5])

In [107]:
mat2 = np.ones([5, 5])


In [108]:
mat3 = mat1 + 2 * mat2

In [109]:
mat4 = mat3
mat3[3][2] = 10

In [110]:
mat5 = np.copy(mat3)
mat3[3][2] = 10

In [112]:
mat6 = np.empty([4, 5])

In [113]:
mat7 = np.identity(4)

In [114]:
mat8 = np.random.random([4, 5])

Bài tập 6

In [116]:
import numpy as np

# Lưới A: Cháy rừng
A = np.array([
    [0, 1, 1, 3, 1],
    [0, 0, 1, 0, 1],
    [1, 5, 2, 2, 0],
    [0, 1, 2, 1, 2]
])

# Lưới B: Lũ quét
B = np.array([
    [1, 1, 2, 2, 2],
    [2, 2, 1, 2, 0],
    [2, 4, 2, 1, 2],
    [2, 2, 2, 2, 2]
])

# Lưới C: Sạt lở núi
C = np.array([
    [0, 5, 0, 1, 1],
    [1, 1, 1, 1, 3],
    [1, 3, 0, 1, 1],
    [3, 3, 0, 2, 2]
])

# Lưới D: Bệnh dịch
D = np.array([
    [3, 1, 5, 0, 1],
    [0, 1, 0, 3, 7],
    [7, 0, 5, 0, 0],
    [3, 5, 3, 5, 3]
])

# Lưới E: Lộ bí mật
E = np.array([
    [1, 0, 0, 0, 0],
    [0, 10, 0, 15, 0],
    [0, 5, 0, 20, 15],
    [5, 0, 0, 5, 0]
])

In [117]:
def map_diem(loai, grid):
    """Chuyển đổi lưới cấp độ thành điểm nguy cơ"""
    if loai == "A":  # Cháy rừng
        return np.select([grid==0, grid==1, grid==2, grid==3, grid==5],
                         [0, 1, 2, 3, 5])
    elif loai == "B":  # Lũ quét
        return np.select([grid==0, grid==1, grid==2, grid==4, grid==8],
                         [0, 1, 2, 4, 8])
    elif loai == "C":  # Sạt lở núi
        return np.select([grid==0, grid==1, grid==3, grid==5, grid==9],
                         [0, 1, 3, 5, 9])
    elif loai == "D":  # Bệnh dịch
        return np.select([grid==0, grid==1, grid==3, grid==5, grid==7],
                         [0, 1, 3, 5, 7])
    elif loai == "E":  # Lộ bí mật
        return np.select([grid==0, grid==5, grid==10, grid==15, grid==20],
                         [0, 5, 10, 15, 20])


In [118]:
A_diem = map_diem("A", A)
B_diem = map_diem("B", B)
C_diem = map_diem("C", C)
D_diem = map_diem("D", D)
E_diem = map_diem("E", E)

In [120]:
NGUONG = 5

In [121]:
tong_a = E_diem
an_toan_a = tong_a <= NGUONG

In [122]:
tong_c = A_diem + D_diem
an_toan_c = tong_c <= NGUONG

In [123]:
tong_e = A_diem + B_diem + C_diem + D_diem + E_diem
an_toan_e = tong_e <= NGUONG

In [126]:
print("Vùng an toàn cho chiến dịch ngắn hạn (a):")
print(an_toan_a.astype(int))  # Chuyển True/False thành 1/0

Vùng an toàn cho chiến dịch ngắn hạn (a):
[[1 1 1 1 1]
 [1 0 1 0 1]
 [1 1 1 0 0]
 [1 1 1 1 1]]
