1. Tóm tắt một số phép xử lý ma trận của NumPy và Scipy

1.1. Một số phép xử lý ma trận của NumPy và Scipy

In [13]:
from scipy import linalg
import numpy as np
a = np.array([1, 2, 3])
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)])
c = np.array([[(0.5, 1.5, 10), (3, 2, 1)], [(6, 5, 4), (7, 8, 9)]])

Các kiểu khai báo và khởi tạo ma trận:

In [14]:
A = np.matrix(np.random.random((2, 2)))
B = np.asmatrix(b)
C = np.asmatrix(np.random.random((10, 5)))
D = np.asmatrix([[4, 3], [2, 6]])
F = np.eye(3, k=1)

In [4]:
F = np.eye(3, k=0)

In [5]:
F = np.eye(3, k=-1)

Các phép xử lý đơn giản

In [6]:
np.linalg.matrix_rank(C)

np.int64(5)

In [7]:
A.I

matrix([[ 12.02645042, -24.45778215],
        [ -6.9314425 ,  17.47563565]])

In [8]:
linalg.inv(A)

array([[ 12.02645042, -24.45778215],
       [ -6.9314425 ,  17.47563565]])

In [9]:
 linalg.det(A)

np.float64(0.024604994417262258)

In [10]:
A.T

matrix([[0.42998792, 0.1705481 ],
        [0.60178359, 0.29591075]])

In [11]:
A.H

matrix([[0.42998792, 0.1705481 ],
        [0.60178359, 0.29591075]])

Giải các loại phương trình tuyến tính:

In [12]:
linalg.solve(A, b)

array([[12.02645042 +10.4069252j ,  0.         -98.2360099j ,
         0.        -110.66734163j],
       [-6.9314425   +7.51956012j,  0.         +73.51529325j,
         0.         +84.0594864j ]])

In [17]:
E = np.asmatrix(a).T

In [18]:
linalg.lstsq(F, E)

(array([[0.],
        [1.],
        [2.]]),
 array([], dtype=float64),
 2,
 array([1., 1., 0.]))

Các hàm trên ma trận

In [19]:
np.add(A, D)

matrix([[4.5740922 , 3.79059254],
        [2.51083478, 6.04468695]])

In [20]:
np.subtract(A, D)

matrix([[-3.4259078 , -2.20940746],
        [-1.48916522, -5.95531305]])

In [21]:
np.divide(A, D)

matrix([[0.14352305, 0.26353085],
        [0.25541739, 0.00744782]])

In [22]:
A @ D

matrix([[3.87755388, 6.46583186],
        [2.13271302, 1.80062604]])

In [23]:
np.multiply(D, A)

matrix([[2.29636879, 2.37177763],
        [1.02166956, 0.2681217 ]])

In [24]:
np.dot(A, D)

matrix([[3.87755388, 6.46583186],
        [2.13271302, 1.80062604]])

In [25]:
np.vdot(A, D)

matrix([[2.29636879]])

Hàm lũy thừa và logarith ma trận:

In [26]:
linalg.expm(A)

array([[2.08828941, 1.16438578],
       [0.75235816, 1.30858064]])

In [27]:
linalg.logm(A)

array([[-0.30006782+0.96681824j,  0.55579274-1.80391327j],
       [ 0.35912084-1.16558352j, -0.67224384+2.17477442j]])

2. Tích (nhân) ma trận với ma trận

2.1. Nhân ma trận

2.2. Ma trận khả nghịch

2.3. Ma trận hội tụ

Ma trận phân kỳ:

In [28]:
import numpy as np
A = np.array([ [0,1], [1,0]])
print(A)

[[0 1]
 [1 0]]


In [29]:
 temp = A.dot(A)
 print(temp)

[[1 0]
 [0 1]]


In [30]:
k= 6
for i in range(k-1):
  temp = temp.dot(A)
  print (temp)
  print('---')

[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---


In [31]:
 B = np.array([ [0,-1], [-1,0]])
 print(B)

[[ 0 -1]
 [-1  0]]


In [ ]:
temp = B.dot(B)

In [32]:
 print(temp)

[[0 1]
 [1 0]]


In [33]:
k= 5
for i in range(k-1):
  temp = temp.dot(B)
  print (temp)
  print('---')

[[-1  0]
 [ 0 -1]]
---
[[0 1]
 [1 0]]
---
[[-1  0]
 [ 0 -1]]
---
[[0 1]
 [1 0]]
---


Ma trận hội tụ - Convergent matrix:

In [34]:
C = np.array([ [1, 0, 0], [0, 0.5, 1], [0, 0, 0.5] ])
print(C)

[[1.  0.  0. ]
 [0.  0.5 1. ]
 [0.  0.  0.5]]


In [35]:
temp = C.dot(C)
print(temp)

[[1.   0.   0.  ]
 [0.   0.25 1.  ]
 [0.   0.   0.25]]


In [36]:
k= 1000
for i in range(k-1):
  temp = temp.dot(C)
print(temp)

[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 4.66631809e-302 9.34196882e-299]
 [0.00000000e+000 0.00000000e+000 4.66631809e-302]]


In [37]:
k= 1000
for i in range(k-1):
 temp = temp.dot(C)
print(temp)

[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


2.4. Ma trận Markov

In [38]:
M = np.array([ [0.8, 0.3], [0.2, 0.7]])
MM = M.dot(M)
print (MM)

[[0.7  0.45]
 [0.3  0.55]]


In [39]:
MM = M.dot(M)
print (MM)

[[0.7  0.45]
 [0.3  0.55]]


In [41]:
for i in range(100):
 MM = MM.dot(M)
print (MM)

[[0.6 0.6]
 [0.4 0.4]]


3. Phương trình ma trận

3.1. Khái niệm về tách ma trận

3.2. Phân rã ma trận LU

In [42]:
M = np.array([ [0.8, 0.3], [0.2, 0.7]])
P, L, U = linalg.lu(M)
print (P)

[[1. 0.]
 [0. 1.]]


In [43]:
print (L)

[[1.   0.  ]
 [0.25 1.  ]]


In [44]:
print (U)

[[0.8   0.3  ]
 [0.    0.625]]


In [45]:
L.dot(U)

array([[0.8, 0.3],
       [0.2, 0.7]])

4. Bài toán ứng dụng 1 – Căn bản về mật mã học, mã hóa thông tin, mật khẩu

Giải thích tại sao ma trận phải khả nghịch trong phương pháp này:
Ma trận phải khả nghịch (có ma trận nghịch đảo) để đảm bảo rằng quá trình giải mã có thể thực hiện được. Nếu ma trận không khả nghịch (tức là định thức của ma trận bằng 0), sẽ không thể tìm được ma trận nghịch đảo, từ đó không thể khôi phục lại thông điệp gốc từ mã hóa.

Nói cách khác:

Mã hóa: Mã hóa = Văn bản × Ma trận

Giải mã: Văn bản = Mã hóa × Ma trận⁻¹
Nếu không có Ma trận⁻¹, bạn không thể làm ngược lại quá trình mã hóa.

Kết quả 3 : [17, 34, 5] → [124, -22, -20]

Kết quả 4 : [0, 6, 26] → [38, -32, -98]

Kết quả 5 : [33, 0, 14] → [113, 19, -122]

Kết quả 6 : [12, 9, 34] → [88, -31, -151]

Kết quả 7 : [25, 35, 35] → [180, -45, -155]

5. Bài toán ứng dụng 2 – Bài toán loan tin

In [46]:
A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]])
temp = A.dot(A)
print(temp)

[[1 1 1 0]
 [1 0 0 1]
 [1 2 0 1]
 [0 1 1 1]]


In [47]:
 temp = temp.dot(A)
 print(temp)

[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]


In [48]:
A = np.array([[0, 1, 0, 1],[0, 0, 1, 0],[1, 0, 0, 1],[1, 1, 0, 0]])
sumA = A
temp = A.dot(A)
k = 3
sumA = sumA + temp
for i in range(1, k-1):
    temp = temp.dot(A)
    sumA = sumA + temp
print(temp)
print(sumA)

[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]
[[2 3 2 3]
 [2 2 1 2]
 [3 4 2 3]
 [3 3 2 2]]


BÀI TẬP CHƯƠNG 3

Câu 1:

In [49]:
import numpy as np

A = np.array([[2, 1, 1],
              [1, 3, 2],
              [1, 0, 1]])

text = "NGUYEN VAN A"

def char_to_num(c):
    return 0 if c == ' ' else ord(c) - ord('A') + 1

def num_to_char(n):
    return ' ' if n == 0 else chr(n + ord('A') - 1)

nums = [char_to_num(c) for c in text.upper()]
while len(nums) % 3 != 0:
    nums.append(0)

vectors = [np.array(nums[i:i+3]) for i in range(0, len(nums), 3)]

encoded = [A.dot(v) for v in vectors]
print("Mã hóa:", encoded)

decoded = [np.round(np.linalg.inv(A).dot(v)).astype(int) for v in encoded]
result = ''.join([num_to_char(n) for vec in decoded for n in vec])
print("Giải mã:", result)

Mã hóa: [array([56, 77, 35]), array([69, 68, 39]), array([23, 68,  1]), array([29, 16, 15])]
Giải mã: NGUYEN VAN A


Câu 2:

a. Chương trình tính
𝑝
𝑛
p
n
​
 ,
𝑞
𝑛
q
n

In [54]:
import numpy as np

def continued_fraction(c_list):
    vec = np.array([[1], [0]])
    for c in reversed(c_list):
        mat = np.array([[c, 1],
                        [1, 0]])
        vec = np.matmul(mat, vec)
    p_n = vec[0, 0]
    q_n = vec[1, 0]
    return p_n, q_n

c = [3, 1, 2]
pn, qn = continued_fraction(c)
print(f"p_n = {pn}, q_n = {qn}, phân số = {pn}/{qn}")

p_n = 11, q_n = 3, phân số = 11/3


b. Chứng minh công thức

## Chứng minh công thức tính \( p_n \), \( q_n \) bằng phương pháp quy nạp

Ta chứng minh bằng **quy nạp** theo \( n \).

### Bước cơ sở: \( n = 0 \)

\[
\begin{pmatrix}
c_0 & 1 \\
1 & 0
\end{pmatrix}
\begin{pmatrix}
1 \\
0
\end{pmatrix}
=
\begin{pmatrix}
c_0 \\
1
\end{pmatrix}
\Rightarrow p_0 = c_0, \quad q_0 = 1
\]

### Giả sử: Công thức đúng với \( n = k \), tức là:

\[
\prod_{i=0}^{k}
\begin{pmatrix}
c_i & 1 \\
1 & 0
\end{pmatrix}
\begin{pmatrix}
1 \\
0
\end{pmatrix}
=
\begin{pmatrix}
p_k \\
q_k
\end{pmatrix}
\]

### Bước suy luận: \( n = k + 1 \)

Nhân thêm ma trận:

\[
\begin{pmatrix}
c_{k+1} & 1 \\
1 & 0
\end{pmatrix}
\begin{pmatrix}
p_k \\
q_k
\end{pmatrix}
=
\begin{pmatrix}
c_{k+1}p_k + q_k \\
p_k
\end{pmatrix}
=
\begin{pmatrix}
p_{k+1} \\
q_{k+1}
\end{pmatrix}
\]

→ Công thức được chứng minh đúng với mọi \( n \in \mathbb{N} \).
