CHƯƠNG 8: KHÔNG GIAN VECTOR VÀ ÁNH XẠ TUYẾN TÍNH
(PHẦN 2)

1. Các bài toán cơ bản về không gian vector

1.1.Một số lưu ý

1.2.Các bài toán tính toán

Bài tập 1:

a.

In [1]:
import numpy as np
u = np.array([2, -1, 5, 0])
v = np.array([4, 3, 1, -1])
w = np.array([-6, 2, 0, 3])
x = 2*u - (v + 3*w)
print(x)

[ 18 -11   9  -8]


b.

In [3]:
x = 0.5*(2*u-v-3*w)
print (x)

[ 9.  -5.5  4.5 -4. ]


Bài toán 2:

In [45]:
import numpy as np
A = np.matrix([[0, -1, 3], [1, 1, 1], [4, 2, 2]])
B = np.array([-1, -2, -2])
X = np.linalg.solve(A, B)
print(X)

[ 1. -2. -1.]


Bài toán 3:

In [11]:
A = np.matrix([[1, 0], [0, 0]])
B = np.matrix([[0, 0], [0, 1]])
from numpy import linalg as LA

In [12]:
LA.inv(A)

LinAlgError: Singular matrix

Ma trận không khả nghịch

Không tồn tại ma trận nghịch đảo

In [13]:
LA.inv(B)

LinAlgError: Singular matrix

ma trận không khả nghịch

In [46]:
LA.inv(A+B)

matrix([[ 0.        ,  0.        ,  0.33333333],
        [-0.25      , -0.25      , -0.08333333],
        [ 0.25      , -0.75      ,  0.08333333]])

In [48]:
LA.det(A)

np.float64(-7.999999999999998)

In [15]:
LA.det(B)

np.float64(0.0)

In [16]:
LA.det(A+B)

np.float64(1.0)

Bài toán 4:

In [17]:
import sympy as sp
x, y = sp.symbols('x y')
A = sp.Matrix([[x, y], [y, x]])
x1, y1 = sp.symbols('x1 y1')
A1 = sp.Matrix([[x1, y1], [y1, x1]])
x2, y2 = sp.symbols('x2 y2')
A2 = sp.Matrix([[x2, y2], [y2, x2]])
A1.T

Matrix([
[x1, y1],
[y1, x1]])

In [18]:
(A1+A2).T

Matrix([
[x1 + x2, y1 + y2],
[y1 + y2, x1 + x2]])

In [19]:
((A1+A2).T).equals(A1+A2)

True

In [20]:
c = sp.symbols('c')
print (c*A)

Matrix([[c*x, c*y], [c*y, c*x]])


In [21]:
((c*A).T).equals(c*A)

True

Bài toán 5:

In [26]:
import sympy as sp

c1, c2, c3 = sp.symbols('c1 c2 c3')
v1 = sp.Matrix([1, 2, 3])
v2 = sp.Matrix([0, 1, 2])
v3 = sp.Matrix([-1, 0, 1])

a.

In [29]:
w1 = sp.Matrix([1, 1, 1])
eq1 = sp.Eq(c1*v1 + c2*v2 + c3*v3, w1)
sol1 = sp.solve(eq1, (c1, c2, c3))
print("a. Nghiệm hệ: ", sol1)

a. Nghiệm hệ:  {c1: c3 + 1, c2: -2*c3 - 1}


b.

In [28]:
w2 = sp.Matrix([1, -2, 2])
eq2 = sp.Eq(c1*v1 + c2*v2 + c3*v3, w2)
sol2 = sp.solve(eq2, (c1, c2, c3))
print("b. Nghiệm hệ: ", sol2)

b. Nghiệm hệ:  []


Bài toán 6:

In [30]:
import sympy as sp
c1, c2, c3 = sp.symbols('c1 c2 c3')
sp.solve([c1 - 2*c3, 2*c1 + c2, 3*c1 + 2*c2 + c3], [c1, c2, c3])

{c1: 0, c2: 0, c3: 0}

Bài toán 7:

In [31]:
import sympy as sp
c1, c2 = sp.symbols('c1 c2')
u1, u2 = sp.symbols('u1 u2')
sp.solve([c1 + c2 - u1, c1 - c2 - u2])

{c1: u1/2 + u2/2, c2: u1/2 - u2/2}

In [32]:
u1 = 0
u2 = 0
sp.solve([c1 + c2 - u1, c1 - c2 - u2])

{c1: 0, c2: 0}

2. Ánh xạ tuyến tính

2.1.Định nghĩa, tính chất và biểu diễn ma trận ánh xạ tuyến tính

2.2.Bài toán ứng dụng: Ma trận biến đổi (ảnh/font chữ/…)

a.

In [33]:
import numpy as np
P = np.array([[0, 0, 3, 3, 1, 1, 2, 2, 1, 1],
              [0, 5, 5, 4, 4, 3, 3, 2, 2, 0]])
vecdelta = np.array([4, 2])
P_caua = (P.T + vecdelta).T
print(P_caua)

[[4 4 7 7 5 5 6 6 5 5]
 [2 7 7 6 6 5 5 4 4 2]]


b.

In [ ]:
import numpy as np
P = np.array([[0, 0, 3, 3, 1, 1, 2, 2, 1, 1],
              [0, 5, 5, 4, 4, 3, 3, 2, 2, 0]])
vecdelta = np.array([4, -2])
matran_biendoi = np.array([[1.0, 0.0],
                           [0.0, 2.0]])
P_caub = (P.T @ matran_biendoi + vecdelta).T
print(P_caub)

c.

In [ ]:
import numpy as np
P = np.array([[x1, x2, ..., xn],
              [y1, y2, ..., yn]])
mat_bien_doi = np.array([[-1, 0],
                         [ 0, 1]])
vec_tinh_tien = np.array([a, b])
P_moi = (P.T @ mat_bien_doi + vec_tinh_tien).T
print(P_moi)

d.

In [ ]:
import numpy as np
P = np.array([[1, 2, 3],
              [4, 5, 6]])
p = 2
q = -1
a = 3
b = 1
mat_shearing = np.array([[1, p],
                         [q, 1]])
vec_tinhtien = np.array([a, b])
P_moi = (P.T @ mat_shearing + vec_tinhtien).T
print(P_moi)

In [34]:
mat_doi_x = np.array([[-1, 0],
                      [ 0, 1]])
P_moi = mat_doi_x @ P
print(P_moi)

[[ 0  0 -3 -3 -1 -1 -2 -2 -1 -1]
 [ 0  5  5  4  4  3  3  2  2  0]]


In [35]:
mat_doi_yx = np.array([[0, 1],
                       [1, 0]])
P_moi = mat_doi_yx @ P
print(P_moi)

[[0 5 5 4 4 3 3 2 2 0]
 [0 0 3 3 1 1 2 2 1 1]]


3. [Đọc thêm] Kiểm lý thuyết về ánh xạ tuyến tính

3.1.Kiểm tra một ánh xạ là ánh xạ tuyến tính

In [36]:
import sympy as sp
from sympy import lambdify
x1, x2, x3 = sp.symbols('x1 x2 x3')
bieuthuc1 = x1 - x2 + x3
f1 = lambdify([x1, x2, x3], bieuthuc1, 'numpy')
a, b, c = sp.symbols('a b c')
d, e, f = sp.symbols('d e f')
f1(a, b, c)

a - b + c

In [37]:
f1(d, e, f)

d - e + f

In [39]:
f1(a+d, b+e, c+f)

a - b + c + d - e + f

In [40]:
f1(a,b,c) + f1(d,e,f) == f1(a+d, b+e, c+f)

True

In [41]:
(f1(a,b,c) + f1(d,e,f)).equals( f1(a+d, b+e, c+f))

True

In [42]:
q = sp.symbols('q')
(q*f1(a,b,c) + f1(d,e,f)).equals(f1(q*a+d, q*b+e, q*c+f).expand())

True

In [43]:
bieuthuc2 = 2*x2 + 3*x3
f2 = lambdify([x1, x2, x3], bieuthuc2, 'numpy')
(q*f2(a, b, c) + f2(d, e, f)).equals(f2(q*a + d, q*b + e, q*c + f).expand())

True

3.2.Tìm tổ hợp tuyến tính cho một ánh xạ tuyến tính

In [ ]:
import sympy as sp
alpha, beta = sp.symbols('alpha beta')
he_pt = [
    sp.Eq(alpha*1 + beta*3, 4),
    sp.Eq(alpha*2 + beta*5, 5)
]
nghiem = sp.solve(he_pt, (alpha, beta))
print(nghiem)
f_u1 = sp.Matrix([1, 1, 2])
f_u2 = sp.Matrix([4, 2, 1])
f_u3 = nghiem[alpha]*f_u1 + nghiem[beta]*f_u2
print(f_u3)

3.3.Tìm ánh xạ tuyến tính

In [ ]:
import sympy as sp
a, b = sp.symbols('a b')
x, y = sp.symbols('x y')
sp.solve([a + 3*b - x, 2*a + 5*b - y], [a, b])

In [49]:
fu1 = np.array([1, 1, 2])
fu2 = np.array([4, 2, 1])
fu = a * fu1 + b * fu2
print(fu)

[a + 4*b a + 2*b 2*a + b]


In [50]:
fu = a.subs(a, -5*x + 3*y)*fu1 + b.subs(b, 2*x - y)*fu2
print (fu)

[3*x - y -x + y -8*x + 5*y]


3.4.Tìm nhân của ánh xạ tuyến tính

In [51]:
x1, x2, x3 = sp.symbols('x1 x2 x3')
sp.solve([x1 + x2 - x3, 2*x1 + 3*x2 - x3, 3*x1 + 5*x2 - x3], [x1, x2, x3])

{x1: 2*x3, x2: -x3}

3.5.Tìm ảnh của ánh xạ tuyến tính

3.6. Ma trận của ánh xạ tuyến tính trong cặp cơ sở

In [53]:
import sympy as sp
x, y = sp.symbols('x y')
def f(v):
    return sp.Matrix([v[0] - v[1], v[0]])
u1 = sp.Matrix([-1, 1])
u2 = sp.Matrix([1, 0])
v1 = sp.Matrix([1, 2])
v2 = sp.Matrix([1, 3])
fu1 = f(u1)
fu2 = f(u2)
a1, a2 = sp.symbols('a1 a2')
he1 = [sp.Eq(fu1[0], a1*v1[0] + a2*v2[0]),
       sp.Eq(fu1[1], a1*v1[1] + a2*v2[1])]
nghiem1 = sp.linsolve(he1, (a1, a2))
b1, b2 = sp.symbols('b1 b2')
he2 = [sp.Eq(fu2[0], b1*v1[0] + b2*v2[0]),
       sp.Eq(fu2[1], b1*v1[1] + b2*v2[1])]
nghiem2 = sp.linsolve(he2, (b1, b2))
vec1 = list(nghiem1)[0]
vec2 = list(nghiem2)[0]
A = sp.Matrix.hstack(sp.Matrix(vec1), sp.Matrix(vec2))
sp.pprint(A)

⎡-5  2 ⎤
⎢      ⎥
⎣3   -1⎦


In [54]:
import numpy as np
import math
from scipy import linalg as LA
B = np.matrix([[1.0/math.sqrt(2), 1.0/math.sqrt(2)],
               [-1.0/math.sqrt(2), 1.0/math.sqrt(2)]])
LA.orth(B)
1.0 / math.sqrt(2)

0.7071067811865475

4. Bài toán ứng dụng: Đường conic và các phép biến đổi

In [55]:
import numpy as np
theta = np.pi / 4
cos_theta = np.cos(theta)
sin_theta = np.sin(theta)
R = np.array([[cos_theta, sin_theta],
              [-sin_theta, cos_theta]])
def rotate_coords(x, y):
    coords = np.array([x, y])
    new_coords = R @ coords
    return new_coords
def transform_conic_equation(xp, yp):
    x = (xp - yp) / np.sqrt(2)
    y = (xp + yp) / np.sqrt(2)
    result = (5 * x**2
              - 6 * x * y
              + 5 * y**2
              + 14 * np.sqrt(2) * x
              - 2 * np.sqrt(2) * y
              + 18)
    return result
xp, yp = 0, 0
value = transform_conic_equation(xp, yp)
print("Giá trị phương trình sau biến đổi tại (x'=0, y'=0):", value)

Giá trị phương trình sau biến đổi tại (x'=0, y'=0): 18.0


BÀI TẬP CHƯƠNG 8

Câu 1:

Ánh xạ không tuyến tính vì có thành phần hằng số
+
2
+2

Câu 2:

In [56]:
import numpy as np
A = np.array([[0, 1],
              [1, -1]])

F = np.array([[1, 1],
              [2, 2],
              [3, 1],
              [4, 3]])
F_transformed = F @ A.T
print(F_transformed)

[[1 0]
 [2 0]
 [1 2]
 [3 1]]


Câu 3:

In [57]:
from sympy import symbols, Matrix
v1, v2, c = symbols('v1 v2 c')
T = Matrix([v1 - v2, v1 + 2*v2])
u1, u2 = symbols('u1 u2')
U = Matrix([u1 - u2, u1 + 2*u2])
T_sum = Matrix([(v1 + u1) - (v2 + u2), (v1 + u1) + 2*(v2 + u2)])
sum_result = T + U
scaled_T = Matrix([c*(v1 - v2), c*(v1 + 2*v2)])
T_scaled = Matrix([(c*v1 - c*v2), (c*v1 + 2*c*v2)])
print(T_sum.equals(sum_result))
print(T_scaled.equals(scaled_T))

True
True


Câu 4:

In [58]:
import numpy as np
A = np.array([[13, -5],
              [-5, 13]])
eigenvalues, eigenvectors = np.linalg.eig(A)
theta_rad = np.arctan2(eigenvectors[1, 0], eigenvectors[0, 0])
theta_deg = np.degrees(theta_rad) % 180
print("Giá trị riêng:", eigenvalues)
print("Vector riêng:", eigenvectors)
print("Góc xoay (độ):", theta_deg)

Giá trị riêng: [18.  8.]
Vector riêng: [[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]
Góc xoay (độ): 135.0
