CHƯƠNG 6: CÁC KHÁI NIỆM: KHÔNG GIAN VECTOR,
TÍCH TRONG VÀ TRỊ RIÊNG, VECTOR RIÊNG

1. Khái niệm về không gian vector và tích trong

1.1.Tóm tắt lý thuyết

1.2.Tích vô hướng, trực giao và ứng dụng

In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
tich = np.inner(a, b)
print(tich)

32


In [2]:
np.dot(a,b)

np.int64(32)

- Độ dài/chuẩn của vector:

In [5]:
import numpy as np

a = np.array([1, 2, -3])
norm = np.linalg.norm(a)
print(norm)

3.7416573867739413


In [6]:
a = np.array([1, 2, -3])
np.linalg.norm(a, 1)

np.float64(6.0)

In [21]:
import numpy as np
def chuan(a, p):
    return np.linalg.norm(a, ord=p)
a = np.array([1, 2, -3])
print(chuan(a, 1))

6.0


In [22]:
np.linalg.norm(a,1)

np.float64(6.0)

In [23]:
chuan(a, 2)

np.float64(3.7416573867739413)

In [24]:
np.linalg.norm(a,2)

np.float64(3.7416573867739413)

In [25]:
chuan(a, 3)

np.float64(3.3019272488946263)

In [26]:
np.linalg.norm(a,3)

np.float64(3.3019272488946263)

In [27]:
chuan(a, 1000)

/usr/local/lib/python3.11/dist-packages/numpy/linalg/_linalg.py:2780: RuntimeWarning: overflow encountered in power
  absx **= ord


np.float64(inf)

In [28]:
np.linalg.norm(a,1000)

/usr/local/lib/python3.11/dist-packages/numpy/linalg/_linalg.py:2780: RuntimeWarning: overflow encountered in power
  absx **= ord


np.float64(inf)

Nguyên nhân: Khi tính chuẩn bậc 1000, giá trị quá lớn nên gây tràn số học (overflow). Kết quả trả về là inf (vô cùng).

In [29]:
from scipy import linalg
linalg.norm(a)

np.float64(3.7416573867739413)

In [30]:
linalg.norm(a, 100)

np.float64(3.0)

In [31]:
linalg.norm(a, 1000)

/usr/local/lib/python3.11/dist-packages/numpy/linalg/_linalg.py:2780: RuntimeWarning: overflow encountered in power
  absx **= ord


np.float64(inf)

2. Đọc thêm: Tổ hợp tuyến tính

In [32]:
import numpy as np

m = 10
v1 = np.array([5, -4, 3])
v2 = np.array([4, 3, -2])
v3 = np.array([-4, -3, -1])
v4 = np.array([-9, 8, 6])
mi = np.array([2, 5, 2, 1])
M = np.array([v1, v2, v3, v4])
MT = M.transpose()
MT

array([[ 5,  4, -4, -9],
       [-4,  3, -3,  8],
       [ 3, -2, -1,  6]])

In [33]:
v = (1.0/m)*MT.dot(mi)

In [34]:
print (v)

[1.3 0.9 0. ]


3. Tri riêng, vector riêng của ma trận và ứng dụng

3.1.Bài toán dẫn nhập

In [36]:
import numpy as np
A = np.array([[0.998, 0.136],
              [0.002, 0.864]])

In [37]:
v0 = np.array([0.95, 0.05])

In [38]:
A_100 = np.linalg.matrix_power(A, 100)

In [39]:
v100 = A_100 @ v0

In [40]:
print(v100)

[0.98550723 0.01449277]


Trạng thái cân bằng (Markov)

In [41]:
import numpy as np

A = np.array([[1, -68],
              [1,  1]])

v = np.array([0, 1])

nghiem = np.linalg.solve(A, v)
print(nghiem)

[0.98550725 0.01449275]


In [42]:
import sympy as sym
x, y = sym.symbols('x y')
xy = sym.Matrix([x, y])
A = sym.Matrix([[1, -68], [1, 1]])
v = sym.Matrix([0, 1])
nghiem = sym.solve([A * xy - v])
print(sym.pretty(nghiem))

⎧   68         ⎫
⎨x: ──, y: 1/69⎬
⎩   69         ⎭


3.2.Trị riêng và vector riêng của ma trận

In [43]:
import sympy as sym

A = sym.Matrix([[1, 5],
                [6, 2]])

u = sym.Matrix([6, -5])

ket_qua = A * u
so_sanh = -4 * u

print("Au =")
sym.pprint(ket_qua)
print("\n-4u =")
sym.pprint(so_sanh)

print("\nKiểm tra Au == -4u:", ket_qua == so_sanh)

Au =
⎡-19⎤
⎢   ⎥
⎣26 ⎦

-4u =
⎡-24⎤
⎢   ⎥
⎣20 ⎦

Kiểm tra Au == -4u: False


In [44]:
import sympy
x, y, Lambda = sympy.symbols('x y Lambda')
I = sympy.eye(2)
A = sympy.Matrix([[2, 3], [3, -6]])
phuongtrinh = sympy.Eq(sympy.det(Lambda*I - A), 0)
nghiem = sympy.solve(phuongtrinh)
print([sympy.N(phantu, 4) for phantu in nghiem])

[-7.000, 3.000]


In [45]:
print (sympy.pretty(nghiem))

[-7, 3]


In [46]:
import sympy as sym

x1, x2 = sym.symbols('x1 x2')
x = sym.Matrix([x1, x2])
A = sym.Matrix([[2, 3], [3, -6]])
I = sym.eye(2)
lambda_val = 3

pt = (A - lambda_val * I) * x
nghiem = sym.solve([pt[0], pt[1]], (x1, x2), dict=True)
print(nghiem)

[{x1: 3*x2}]


3.3.Ứng dụng của trị riêng và vector riêng

In [47]:
import numpy as np
from numpy import linalg as LA

A = np.array([[2, 3], [3, -6]])
D = np.array([[-7, 0], [0, 3]])
P = np.array([[-1.0/3, 3], [1, 1]])

P1 = LA.inv(P)
print(P1)

[[-0.3  0.9]
 [ 0.3  0.1]]


In [48]:
print(np.dot(A, P))

[[ 2.33333333  9.        ]
 [-7.          3.        ]]


In [49]:
print(np.dot(P, D))

[[ 2.33333333  9.        ]
 [-7.          3.        ]]


In [50]:
A1000 = P @ (D ** 1000) @ P1
print(A1000)

[[ 5.03503397e+18  3.50482117e+18]
 [ 3.50482117e+18 -4.31115581e+18]]


In [51]:
print (D **2)

[[49  0]
 [ 0  9]]


BÀI TẬP CHƯƠNG 6

Câu 1

In [52]:
import numpy as np
a = np.array([1,2,3])

câu lệnh được tính chuẩn bậc 2 là a. >>> mag = np.sqrt(a.dot(a))

Câu 2:

a. Tính khoảng cách giữa 2 vector
∥
𝑢
−
𝑣
∥
∥u−v∥

In [53]:
import numpy as np

u = np.array([1, 2, 3])
v = np.array([4, 0, -1])

distance = np.linalg.norm(u - v)
print("Khoảng cách:", distance)

Khoảng cách: 5.385164807134504


b. Tính góc θ giữa 2 vector (đơn vị: radian)

In [54]:
dot = np.dot(u, v)
norm_u = np.linalg.norm(u)
norm_v = np.linalg.norm(v)

cos_theta = dot / (norm_u * norm_v)
theta = np.arccos(cos_theta)

print("Góc θ (radian):", theta)

Góc θ (radian): 1.5059304759807983


c. Phép chiếu trực giao của u lên v

In [55]:
projection = (np.dot(u, v) / np.dot(v, v)) * v
print("Phép chiếu u lên v:", projection)

Phép chiếu u lên v: [ 0.23529412  0.         -0.05882353]
