1. Dẫn nhập – Một số hàm về xử lý vector với Python

In [13]:
def scale(a, v):
    return [a * vi for vi in v]

v = [3, 5, 7]
scale(10, v)

[30, 50, 70]

In [14]:
def sumvector(v, w):
    return [vi + wi for (vi, wi) in zip(v, w)]

v = [3, 5, 7]
w = [2, 4, 6]
sumvector(v, w)

[5, 9, 13]

In [15]:
def dotvector(v, w):
    return sum([vi * wi for (vi, wi) in zip(v, w)])

dotvector(v, w)

68

In [17]:
def lenvector(v):
    return dotvector(v, v)

lenvector(w)

56

2. Bài toán ứng dụng 1 – Phân loại tuyến tính

In [19]:
import numpy as np
scores = np.array([-1, 1, 2, -3, 5, -4])

In [20]:
scores >= 0

array([False,  True,  True, False,  True, False])

In [21]:
scores < 0

array([ True, False, False,  True, False,  True])

In [26]:
import numpy as np

scores = np.array([-1, 1, 2, -3, 5, -4])
result = np.select(
    [scores >= 0, scores < 0],
    ['so duong', 'so am'],
    default='khong xac dinh'
)

print(result)


['so am' 'so duong' 'so duong' 'so am' 'so duong' 'so am']


In [27]:
scores = np.array([-1, 1, 2, 0, -3, 5, 0, -4])
result = np.select(
    [scores > 0, scores == 0, scores < 0],
    ['so duong', 'so 0', 'so am'],
    default='khong xac dinh'
)

print(result)

['so am' 'so duong' 'so duong' 'so 0' 'so am' 'so duong' 'so 0' 'so am']


3. Thực hành xử lý ma trận

In [44]:
import numpy as np
from scipy import linalg, sparse

In [43]:
D = np.asmatrix([[3, 4], [5, 6]])
print(D)

[[3 4]
 [5 6]]


In [42]:
C = np.array(np.random.random((5, 7)))
print(C)

[[0.2222322  0.91505403 0.91986512 0.52426328 0.8556015  0.81422507
  0.86595471]
 [0.91952576 0.93958728 0.90490296 0.63159241 0.31509859 0.96679449
  0.21282394]
 [0.73761274 0.33558301 0.00308639 0.14493538 0.44102929 0.76282529
  0.49447032]
 [0.28644334 0.17573575 0.69863085 0.53527569 0.10325635 0.84949519
  0.23653643]
 [0.09995184 0.53522889 0.69447402 0.93566238 0.8885241  0.26705194
  0.08017128]]


In [41]:
A = np.array(np.random.random((2, 2)))
print(A)

[[0.64984964 0.54069566]
 [0.88802098 0.72455833]]


In [45]:
b = np.array([[1+5j, 2j, 3j], [4, 5, 6]], dtype=complex)
B = np.asmatrix(b)
print("b =")
print(b)
print("B =")
print(B)

b =
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]
B =
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [46]:
print("A.T =")
print(A.T)

A.T =
[[0.64984964 0.88802098]
 [0.54069566 0.72455833]]


In [47]:
print("Nghịch đảo A bằng np.linalg.inv(A):")
print(np.linalg.inv(A))

Nghịch đảo A bằng np.linalg.inv(A):
[[-77.95044455  58.1698739 ]
 [ 95.53631086 -69.91302991]]


In [48]:
M = np.array([[-1, 3, 2], [0, -2, 1], [1, 5, -2]])
M_lower = np.tril(M)
print("Ma trận dưới:")
print(M_lower)

Ma trận dưới:
[[-1  0  0]
 [ 0 -2  0]
 [ 1  5 -2]]


In [49]:
M_upper = np.triu(M)
print("Ma trận trên:")
print(M_upper)

Ma trận trên:
[[-1  3  2]
 [ 0 -2  1]
 [ 0  0 -2]]


In [50]:
v_diag = np.diag(M)
print("Vector đường chéo:")
print(v_diag)

M_diag = np.diag(v_diag)
print("Ma trận đường chéo:")
print(M_diag)

Vector đường chéo:
[-1 -2 -2]
Ma trận đường chéo:
[[-1  0  0]
 [ 0 -2  0]
 [ 0  0 -2]]


Bài tập dẫn nhập

In [53]:
from sympy import symbols, Eq, solve

x, y, z = symbols('x y z')

eq1 = Eq(x + 2, 6)
eq2 = Eq(x + z, 1)
eq3 = Eq(2 * x, 8)
eq4 = Eq(y + 4, 5)
eq5 = Eq(-z, 8)

sol = solve([eq1, eq2, eq3, eq4, eq5], (x, y, z))
print(sol)


[]


In [52]:
import sympy as sp
x = sp.Symbol('x')
y = sp.Symbol('y')
z = sp.Symbol('z')

sp.solve([
    x + 2 - 6,
    y - 1 - 6,
    x + z - 1,
    2 * x - 8,
    z + 4 - 5,
    y - z - 8
], [x, y, z])

[]

3.2. Các phép biến đổi sơ cấp trên ma trận

In [54]:
import numpy as np

A = np.reshape(np.arange(36.0), (6,6))
print(A)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]


In [55]:
I6 = np.identity(6)
print(I6)


[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [56]:
A.size


36

In [57]:
np.diagonal(A)


array([ 0.,  7., 14., 21., 28., 35.])

In [58]:
A = A + I6
print(A)


[[ 1.  1.  2.  3.  4.  5.]
 [ 6.  8.  8.  9. 10. 11.]
 [12. 13. 15. 15. 16. 17.]
 [18. 19. 20. 22. 22. 23.]
 [24. 25. 26. 27. 29. 29.]
 [30. 31. 32. 33. 34. 36.]]


In [59]:
vecB = np.array([1., 2., 3., 4., 5., 6.])
C = A.dot(vecB)
print(C)


[ 71. 198. 325. 452. 579. 706.]


In [60]:
D = np.array([[1., 2., 3., 4., 5., 6.], [1., 0., 1., 0., 1., 0.]])
print(D)


[[1. 2. 3. 4. 5. 6.]
 [1. 0. 1. 0. 1. 0.]]


In [62]:
E = A.dot(D.T)
print(E)


[[ 71.   7.]
 [198.  24.]
 [325.  43.]
 [452.  60.]
 [579.  79.]
 [706.  96.]]


In [63]:
F = np.array([
    [1., 1.],
    [2., 0.],
    [3., 1.],
    [4., 0.],
    [5., 1.],
    [6., 0.]
])
print(F)


[[1. 1.]
 [2. 0.]
 [3. 1.]
 [4. 0.]
 [5. 1.]
 [6. 0.]]


In [64]:
G = A.dot(F)
print(G)


[[ 71.   7.]
 [198.  24.]
 [325.  43.]
 [452.  60.]
 [579.  79.]
 [706.  96.]]


In [65]:
A_inv = np.linalg.inv(A)
print(A_inv)


[[ 0.37022901 -0.45610687 -0.28244275 -0.10877863  0.0648855   0.23854962]
 [-0.44656489  0.65839695 -0.23664122 -0.13167939 -0.02671756  0.07824427]
 [-0.26335878 -0.22709924  0.80916031 -0.15458015 -0.11832061 -0.08206107]
 [-0.08015267 -0.11259542 -0.14503817  0.82251908 -0.20992366 -0.24236641]
 [ 0.10305344  0.0019084  -0.09923664 -0.20038168  0.69847328 -0.40267176]
 [ 0.28625954  0.11641221 -0.05343511 -0.22328244 -0.39312977  0.4370229 ]]


In [66]:
np.linalg.inv(np.linalg.inv(A))


array([[ 1.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  8.,  8.,  9., 10., 11.],
       [12., 13., 15., 15., 16., 17.],
       [18., 19., 20., 22., 22., 23.],
       [24., 25., 26., 27., 29., 29.],
       [30., 31., 32., 33., 34., 36.]])

4. Bài toán ứng dụng 2 – Tính toán dãy Fibonacci: Con đường tìm đến tỉ số vàng!

In [67]:
import numpy as np
A = np.array([[1,1], [1,0]])
b = np.array([1, 0])
n = 10
for i in range(n):
    b = A.dot(b)
    print(b)


[1 1]
[2 1]
[3 2]
[5 3]
[8 5]
[13  8]
[21 13]
[34 21]
[55 34]
[89 55]


5. Cơ bản về hệ phương trình tuyến tính và ứng dụng minh họa

In [68]:
import sympy as sp
x1, x2, x3, x4 = sp.symbols('x1 x2 x3 x4')

pt1 = x4 + 610 - 450 - x1
pt2 = x1 + 400 - x2 - 640
pt3 = x2 + 600 - x3
pt4 = x3 - x4 - 520

nghiem = sp.solve((pt1, pt2, pt3, pt4))
print(nghiem)


{x1: x4 + 160, x2: x4 - 80, x3: x4 + 520}


In [70]:
from sympy import Symbol, solve

x1 = Symbol('x1')
x2 = Symbol('x2')
x3 = Symbol('x3')
x4 = Symbol('x4')

pt1 = x4 + 610 - 450 - x1
pt2 = x1 + 400 - x2 - 640
pt3 = x2 + 600 - x3
pt4 = x3 - x4 - 520

nghiem = solve((pt1, pt2, pt3, pt4))
print(nghiem)

{x1: x4 + 160, x2: x4 - 80, x3: x4 + 520}


In [75]:
import numpy as np
A = np.matrix([[-1,0,0,1],[1,-1,0,0],[0,1,-1,0],[0,0,1,-1]])

In [78]:
import sympy as sp

x1, x2, x3, x4 = sp.symbols('x1 x2 x3 x4')

pt1 = x4 + 610 - 450 - x1
pt2 = x1 + 400 - x2 - 640
pt3 = x2 + 600 - x3
pt4 = x3 - x4 - 520

nghiem = sp.solve((pt1, pt2, pt3, pt4), (x1, x2, x3, x4), dict=True)
print(nghiem)

[{x1: x4 + 160, x2: x4 - 80, x3: x4 + 520}]


BÀI TẬP CHƯƠNG 2

Câu 1:

In [79]:
#Vấn đề 1
import numpy as np

A = np.array([[1, -1], [2, 3]])
B = np.array([2, 6])
x = np.linalg.solve(A, B)
print("Giao điểm:", x)

Giao điểm: [2.4 0.4]


In [80]:
#Vấn đề 2
A = np.array([[1, -1, 0],
              [2, -1, -1],
              [1, 1, 1]])
B = np.array([2, 3, 6])
x = np.linalg.solve(A, B)
print("Giao điểm:", x)

Giao điểm: [3. 1. 2.]


In [81]:
#Vấn đề 3
A = np.array([[1, 1, 1],
              [4, 2, 1],
              [9, 3, 1]])
B = np.array([4, 3, 4])
x = np.linalg.solve(A, B)
print("Hệ số đa thức (a, b, c):", x)

Hệ số đa thức (a, b, c): [ 1. -4.  7.]


In [82]:
#Vấn đề 4
A = np.array([[1, 0, 1],
              [1, 1, -2],
              [-2, 2, 1]])
B = np.array([1, -3, 0])
x = np.linalg.solve(A, B)
print("a, b, c =", x)


a, b, c = [-0.11111111 -0.66666667  1.11111111]


Câu 2:

In [83]:
from sympy import symbols, Eq, solve

x, y = symbols('x y')
eq1 = Eq(x - y, 2)
eq2 = Eq(2*x + 3*y, 6)
sol = solve((eq1, eq2), (x, y))
print("Nghiệm:", sol)

Nghiệm: {x: 12/5, y: 2/5}


Câu 3:

In [84]:
import numpy as np

def fib_matrix(k):
    F = np.array([[1, 1], [1, 0]])
    result = np.linalg.matrix_power(F, k)
    return result

def fib(n):
    if n == 0: return 0
    elif n == 1: return 1
    a, b = 0, 1
    for _ in range(2, n + 1):
        a, b = b, a + b
    return b

k = 5
Fk = fib_matrix(k)
expected = np.array([[fib(k+1), fib(k)],
                     [fib(k), fib(k-1)]])
print("F_k matrix:\n", Fk)
print("Expected matrix:\n", expected)
print("So khớp?", np.array_equal(Fk, expected))

F_k matrix:
 [[8 5]
 [5 3]]
Expected matrix:
 [[8 5]
 [5 3]]
So khớp? True
